---
jupyter: python3
execute:
  eval: false
---

# Базовые операции рендеринга

Визуализация данных в QGIS возможна не только посредством графического интерфейса, но также путем программной компоновки карт. Преимущество программного отображения в QGIS по сравнению с тем, что вы можете сделать на чистом Python --- в том, что становится доступен невероятно мощный функционал и производительность графического движка QGIS.

Первая операция, которая может быть полезной, это получение ссылки на экземпляр проекта:

```{python}
QgsProject.instance()
```

Главное, для чего он может быть полезен --- это управление списком отображаемых слоёв. Можно получить список слоев или удалить все слои из содержимого карты:

```{python}
QgsProject.instance().mapLayers().values() # список слоёв
QgsProject.instance().removeAllMapLayers() # удаление всех слоёв
```

Если необходимо чтобы скрипт собирал карту с нуля каждый раз при запуске, следует расположить вызов `removeAllMapLayers()` в самом начале. Это будет гарантировать, что сборка проекта начнется с чистого листа.

Сборку логично начать с добавления слоёв, которое осуществляется посредством следующей команды:

```{python}
layer = iface.addVectorLayer(path)
layer = iface.addRasterLayer(path)
```

где `path` --- полный путь к данным, `layer` --- переменная, которая будет хранить ссылку на слой в таблице содержания. Вы можете ее называть любым подходящим именем.

Обратите внимание на переменную `iface`. **Это самая важная переменная в скрипте**. Создавать её не нужно, она доступна всегда по умолчанию и представляет собой экземпляр класса `QgsInterface`. Через него вы получаете доступ к компоненте карты, меню панелям инструментов и другим компонентам.
