project:
  type: book
  output-dir: docs

book:
  title: "Визуализация пространственных данных"
  author: "Тимофей Самсонов"
  date: "22.09.2022"
  chapters:
    - index.qmd
    - part: "Лекции"
      chapters: 
        - 01_Fundamentals.qmd
        - 02_Color.qmd
        - 03_Blending.qmd
    - part: "Практикум"
      chapters: 
        - p01_Basics.qmd
        - p02_Scales.qmd
        - p03_Colordist.qmd
        - p04_Rubberband.qmd
  appendices:
    - calibration.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo



