project:
  type: book

book:
  title: "Визуализация пространственных данных"
  author: "Тимофей Самсонов"
  date: "22.09.2022"
  chapters:
    - index.qmd
    - 01_Basics.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo



