project:
  type: book
  output-dir: docs

book:
  title: "Визуализация пространственных данных"
  author: "Тимофей Самсонов"
  date: "22.09.2022"
  chapters:
    - index.qmd
    - 01_Basics.qmd
    - 02_Scales.qmd
    - 03_Colordist.qmd
  appendices:
    - calibration.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo



